# Generated by Django 4.1.4 on 2022-12-28 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KokopelliEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pretty_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='session.session')),
                ('allow_spotify', models.BooleanField(default=True)),
                ('allow_youtube', models.BooleanField(default=True)),
                ('youtube_only_audio', models.BooleanField(default=False)),
                ('allow_events', models.BooleanField(default=True)),
                ('event_frequency', models.IntegerField(default=10)),
                ('random_word_list', models.CharField(default='[]', max_length=1000)),
                ('anyone_can_use_player_controls', models.BooleanField(default=True)),
                ('anyone_can_add_to_queue', models.BooleanField(default=True)),
                ('anyone_can_remove_from_queue', models.BooleanField(default=True)),
                ('anyone_can_see_history', models.BooleanField(default=True)),
                ('anyone_can_see_queue', models.BooleanField(default=True)),
                ('anyone_can_see_playlist', models.BooleanField(default=True)),
                ('algorithm_used', models.CharField(default='random', max_length=255)),
                ('allow_guests', models.BooleanField(default=True)),
                ('allowed_events', models.ManyToManyField(blank=True, to='session.kokopellievent')),
            ],
        ),
    ]
