# Generated by Django 4.1.4 on 2022-12-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist'),
            preserve_default=False,
        ),
    ]
