# Generated by Django 4.1.4 on 2022-12-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
        ('session', '0003_alter_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist'),
        ),
    ]
