# Generated by Django 4.1.4 on 2022-12-28 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_accesstoken_last_used_at'),
        ('session', '0004_alter_session_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
