# Generated by Django 4.1.4 on 2022-12-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_song_play_count'),
        ('session', '0006_currentlyplaying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.song')),
            ],
        ),
    ]
