# Generated by Django 4.1.4 on 2022-12-27 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
