# Generated by Django 4.1.4 on 2022-12-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_accesstoken_created_at_accesstoken_last_used_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='last_used_at',
        ),
    ]
